CONFIG += release warn_on
CONFIG += ordered

OBJECTS_DIR = $$(PLATE_GATEWAY_BUILD)/obj

PLATE_GATEWAY_SANDBOX     = $$(PLATE_GATEWAY_BUILD)
PLATE_GATEWAY_SANDBOX_BIN = $$PLATE_GATEWAY_SANDBOX/bin
PLATE_GATEWAY_SANDBOX_LIB = $$PLATE_GATEWAY_SANDBOX/lib
PLATE_GATEWAY_SANDBOX_SRC = $$PLATE_GATEWAY_SANDBOX/src
PLATE_GATEWAY_SANDBOX_MOC = ./moc_cpp

PLATE_GATEWAY_THIRDPARTY_TESSERACT = $$(PLATE_GATEWAY_THIRDPARTY_TESSERACT)
PLATE_GATEWAY_THIRDPARTY_TESSERACT_LIB = $$PLATE_GATEWAY_THIRDPARTY_TESSERACT/lib
PLATE_GATEWAY_THIRDPARTY_TESSERACT_INC = $$PLATE_GATEWAY_THIRDPARTY_TESSERACT/include
PLATE_GATEWAY_THIRDPARTY_TESSERACT_BIN = $$PLATE_GATEWAY_THIRDPARTY_TESSERACT/bin
PLATE_GATEWAY_THIRDPARTY_TESSERACT_SHR = $$PLATE_GATEWAY_THIRDPARTY_TESSERACT/share

PLATE_GATEWAY_THIRDPARTY_OPENCV = $$(PLATE_GATEWAY_THIRDPARTY_OPENCV)
PLATE_GATEWAY_THIRDPARTY_OPENCV_LIB = $$PLATE_GATEWAY_THIRDPARTY_OPENCV/lib
PLATE_GATEWAY_THIRDPARTY_OPENCV_INC = $$PLATE_GATEWAY_THIRDPARTY_OPENCV/include
PLATE_GATEWAY_THIRDPARTY_OPENCV_BIN = $$PLATE_GATEWAY_THIRDPARTY_OPENCV/bin
PLATE_GATEWAY_THIRDPARTY_OPENCV_SHR = $$PLATE_GATEWAY_THIRDPARTY_OPENCV/share

PLATE_GATEWAY_THIRDPARTY_LEPTONICA = $$(PLATE_GATEWAY_THIRDPARTY_LEPTONICA)
PLATE_GATEWAY_THIRDPARTY_LEPTONICA_LIB = $$PLATE_GATEWAY_THIRDPARTY_LEPTONICA/lib
PLATE_GATEWAY_THIRDPARTY_LEPTONICA_INC = $$PLATE_GATEWAY_THIRDPARTY_LEPTONICA/include
PLATE_GATEWAY_THIRDPARTY_LEPTONICA_BIN = $$PLATE_GATEWAY_THIRDPARTY_LEPTONICA/bin
PLATE_GATEWAY_THIRDPARTY_LEPTONICA_SHR = $$PLATE_GATEWAY_THIRDPARTY_LEPTONICA/share

QMAKE_CXXFLAGS += -fPIC -fmessage-length=0
QMAKE_CFLAGS   += -fPIC -fmessage-length=0 

# Additional optimizations for release build
QMAKE_CXXFLAGS += -finline-functions
QMAKE_CFLAGS   += -finline-functions

QMAKE_LIBDIR_X11 += /usr/X11R6/lib64
QMAKE_CXXFLAGS += -D__STDC_CONSTANT_MACROS 
